// Cleaned aiTools list with grouping helpers
// `tools` is the flat array. `byCategory` groups tools by their `category` string.
// Exposes convenience helpers and attaches to `window` for browser usage.

const tools = [
  // Chat & Conversational AI
  { name: 'ChatGPT', category: 'Chat', description: 'Advanced conversational AI for diverse tasks and dialogue.', url: 'https://chat.openai.com' },
  { name: 'Claude', category: 'Chat', description: 'Intelligent assistant by Anthropic for complex reasoning.', url: 'https://claude.ai' },
  { name: 'Gemini', category: 'Chat', description: 'Google\'s AI model for creative and analytical tasks.', url: 'https://gemini.google.com' },
  { name: 'Copilot', category: 'Chat', description: 'Microsoft\'s AI assistant powered by GPT-4.', url: 'https://copilot.microsoft.com' },
  { name: 'Perplexity AI', category: 'Chat', description: 'Research-focused AI that cites sources in conversations.', url: 'https://www.perplexity.ai' },
  { name: 'Mistral AI', category: 'Chat', description: 'Fast and efficient open-source AI model.', url: 'https://mistral.ai' },
  { name: 'TheQuickAssist', category: 'Chat', description: 'Build and deploy AI chatbots for websites.', url: 'https://www.livechat.com' },
  { name: 'Patter', category: 'Chat', description: 'Build AI chat agents for sales automation.', url: 'https://www.drift.com' },
  { name: 'IntoChat', category: 'Chat', description: 'A chatbot platform for customer support, lead generation, and engagement across multiple channels.', url: '' },
  { name: 'NotebookLM', category: 'Chat', description: 'Chat with your documents and websites.', url: '' },
  { name: 'Sonant', category: 'Chat', description: 'An AI receptionist for insurance agencies phone calls tasks.', url: '' },
  { name: 'AeroChat', category: 'Chat', description: 'A tool that unifies customer communication across channels for brand-consistent support.', url: '' },
  { name: 'HelpLoom', category: 'Chat', description: 'A tool to provide live chat and customer support.', url: '' },
  { name: 'Heyy', category: 'Chat', description: 'A tool for creating customer conversations across messaging platforms using AI agents for sales, marketing, and support.', url: '' },
  { name: 'NeuralTalk AI', category: 'Chat', description: 'A tool to create custom, knowledge-based chatbots that automatically updates with business content.', url: '' },
  { name: 'Zenor.ai', category: 'Chat', description: 'A tool to assist shopify shopping with chat, voice, and video.', url: '' },
  { name: 'Fast Q&A', category: 'Chat', description: 'A tool to answer visitor questions directly on websites.', url: '' },
  { name: 'Release0', category: 'Chat', description: 'A no-code platform for building and deploying conversational experiences across multiple channels.', url: '' },
  { name: 'Ten', category: 'Chat', description: 'A tool to build real-time multimodal conversational AI agents.', url: '' },
  { name: 'Botric AI', category: 'Chat', description: 'A tool for customer service with self learning, context-aware and integrates across digital platforms.', url: '' },
  
  // Generative Art & Image
  { name: 'DALL-E 3', category: 'Generative Art', description: 'Generate detailed images from text descriptions.', url: 'https://openai.com/dall-e-3' },
  { name: 'Midjourney', category: 'Generative Art', description: 'Create high-quality artwork through AI imagination.', url: 'https://www.midjourney.com' },
  { name: 'Stable Diffusion', category: 'Generative Art', description: 'Open-source image generation model.', url: 'https://stablediffusionweb.com' },
  { name: 'Adobe Firefly', category: 'Generative Art', description: 'Generative art within Adobe Creative Suite.', url: 'https://www.adobe.com/products/firefly.html' },
  { name: 'Leonardo AI', category: 'Generative Art', description: 'Create unique production-ready game assets.', url: 'https://leonardo.ai' },
  { name: 'Copilot 3D', category: 'Generative Art', description: 'Convert 2D images into 3D models.', url: 'https://copilot3d.ai' },
  { name: 'LetzAI', category: 'Generative Art', description: 'Creates custom image generators trained on your photos.', url: 'https://letz.ai' },
  { name: 'Vibe3D', category: 'Generative Art', description: 'Turn 3D models into renders with text-based editing.', url: 'https://www.meshy.ai' },
  { name: 'Decor8 AI', category: 'Generative Art', description: 'A tool to generate interior redesigns from room photos.', url: '' },
  { name: 'Form3D', category: 'Generative Art', description: 'A tool to convert online furniture links into SketchUp 3D models.', url: '' },
  { name: 'SVGMaker', category: 'Generative Art', description: 'A tool that converts text descriptions into editable vector graphics.', url: '' },
  { name: 'Montra', category: 'Generative Art', description: 'A tool to generate images and create multi-scene videos.', url: '' },
  { name: 'Txt2Create', category: 'Generative Art', description: 'A tool to create videos, images, and animated content from text.', url: '' },
  { name: 'PhotoFox AI', category: 'Generative Art', description: 'A tool to generate product visuals and videos without traditional photoshoots.', url: '' },
  { name: 'WaveSpeed AI', category: 'Generative Art', description: 'A platform to generate images and videos from text, image, or audio prompts.', url: '' },
  { name: 'CrePal', category: 'Generative Art', description: 'A tool to create and edit images, scripts to produce videos.', url: '' },
  
  // Image Improvement
  { name: 'Daisy.so', category: 'Image Improvement', description: 'Remix, edit, and animate images with custom styles.', url: 'https://daisy.so' },
  { name: 'GetRenders', category: 'Image Improvement', description: 'Create virtual staging for real estate photos.', url: 'https://www.virtualstaging.ai' },
  { name: 'Image MetaHub', category: 'Image Improvement', description: 'A tool to organize and search AI-generated images locally.', url: '' },
  
  // Copywriting & Content
  { name: 'Jasper', category: 'Copywriting', description: 'AI writing assistant for marketing and content creation.', url: 'https://www.jasper.ai' },
  { name: 'Copy.ai', category: 'Copywriting', description: 'Generate marketing copy and social media content.', url: 'https://www.copy.ai' },
  { name: 'Grammarly', category: 'Copywriting', description: 'AI-powered writing assistant for grammar and clarity.', url: 'https://www.grammarly.com' },
  { name: 'Movable Type', category: 'Copywriting', description: 'Generate book manuscripts matching your writing style.', url: 'https://movabletype.ai' },
  { name: 'Writesonic', category: 'Copywriting', description: 'Create SEO content and marketing copy instantly.', url: 'https://writesonic.com' },
  { name: 'Writitude', category: 'Copywriting', description: 'A tool to create and enforce custom writing guidelines with analysis for consistent brand voice.', url: '' },
  { name: 'ReadyScriptPro', category: 'Copywriting', description: 'A tool to generate customized scripts and marketing content.', url: '' },
  { name: 'Content Maxima', category: 'Copywriting', description: 'A marketing suite for SEO content creation from analysis and research.', url: '' },
  
  // Video Generation & Editing
  { name: 'Runway', category: 'Generative Video', description: 'AI video creation and editing suite.', url: 'https://runwayml.com' },
  { name: 'Synthesia', category: 'Generative Video', description: 'Create videos from text with AI avatars.', url: 'https://www.synthesia.io' },
  { name: 'D-ID', category: 'Generative Video', description: 'Generate talking head videos from images.', url: 'https://www.d-id.com' },
  { name: 'Plotaverse', category: 'Generative Video', description: 'Transform static images into animated videos.', url: 'https://plotaverse.com' },
  { name: 'Google Veo', category: 'Generative Video', description: 'Google Veo 3 generates realistic, cinematic videos with audio from text or image prompts.', url: '' },
  { name: 'Bloom Studio', category: 'Generative Video', description: 'A tool to generate product photos and videos for e-commerce.', url: '' },
  { name: 'Anpo AI', category: 'Generative Video', description: 'A tool to turn product photos into lifestyle videos.', url: '' },
  { name: 'Tutorial AI', category: 'Generative Video', description: 'A platform that creates step-by-step guides and demo videos.', url: '' },
  { name: 'DrawMingo', category: 'Generative Video', description: 'A tool that transforms hand-drawn artwork into animated videos with music and effects.', url: '' },
  { name: 'Symvol', category: 'Generative Video', description: 'A tool to convert written articles into video content.', url: '' },
  { name: 'Sora App', category: 'Generative Video', description: 'An iOS App that generates videos from text descriptions.', url: '' },
  { name: 'Tapybl', category: 'Generative Video', description: 'A tool that transforms documents into interactive video lessons with quizzes.', url: '' },
  { name: 'Morphic', category: 'Generative Video', description: 'A tool to generate and edit images, videos, and scenes.', url: '' },
  { name: 'Sync.so', category: 'Generative Video', description: 'A tool to sync lips and clone voices in videos.', url: '' },
  
  // Text-To-Video
  { name: 'Vireel', category: 'Text-To-Video', description: 'Create short-form videos for social media.', url: 'https://vireel.ai' },
  
  // Video Editing
  { name: 'FrameZero', category: 'Video Editing', description: 'Sketch, animate, and share ideas online.', url: 'https://framezero.ai' },
  { name: 'Tight Studio', category: 'Video Editing', description: 'A MacOS Software to create product demo and tutorial videos with auto-zoom, captions, and voiceovers.', url: '' },
  { name: 'Crossfade', category: 'Video Editing', description: 'An video editor to transcribe, highlight, and extract key video segments.', url: '' },
  { name: 'Vidvoi', category: 'Video Editing', description: 'A tool to add voiceovers and captions to videos.', url: '' },
  { name: 'Syllaby', category: 'Video Editing', description: 'Effortlessly Create Viral Videos with Syllaby.io.', url: '' },
  
  // Code Generation
  { name: 'GitHub Copilot', category: 'Generative Code', description: 'AI pair programmer that writes code for you.', url: 'https://github.com/features/copilot' },
  { name: 'Tabnine', category: 'Generative Code', description: 'AI code completion for any programming language.', url: 'https://www.tabnine.com' },
  { name: 'CodeWhisperer', category: 'Generative Code', description: 'AWS\'s AI code recommendation service.', url: 'https://aws.amazon.com/codewhisperer' },
  { name: 'Replit', category: 'Generative Code', description: 'AI-powered IDE for rapid development.', url: 'https://replit.com' },
  { name: 'Open Lovable', category: 'Generative Code', description: 'Convert websites into React applications.', url: 'https://openlovable.com' },
  { name: 'Vibecode', category: 'Generative Code', description: 'Build mobile apps like editing videos.', url: 'https://vibecode.com' },
  { name: 'Cline', category: 'Generative Code', description: 'Open source collaborative coding agent.', url: 'https://github.com/topics/ai-coding' },
  { name: 'Matter AI', category: 'Generative Code', description: 'Automate code reviews and find bugs.', url: 'https://www.codereview.ai' },
  { name: 'Cursor v2', category: 'Generative Code', description: 'Cursor is an AI-powered code editor that helps engineers build software faster.', url: '' },
  { name: 'RoboMonkey', category: 'Generative Code', description: 'A nocode tool to create custom Chrome extensions and browser automations.', url: '' },
  { name: 'Floot', category: 'Generative Code', description: 'A platform to build web apps by describing your ideas to an AI chat.', url: '' },
  { name: 'Dyad', category: 'Generative Code', description: 'An open-source tool to build full-stack apps from natural language.', url: '' },
  { name: 'Lamatic', category: 'Generative Code', description: 'A tool to build and deploy generative AI applications visually.', url: '' },
  { name: 'TestDriver AI', category: 'Generative Code', description: 'A tool to automate software testing across platforms using AI vision.', url: '' },
  { name: 'Unshift AI', category: 'Generative Code', description: 'A visual website builder that converts designs into code and content generation.', url: '' },
  { name: 'Figmentor', category: 'Generative Code', description: 'A tool that converts Figma designs into Elementor WordPress templates.', url: '' },
  { name: 'Telex', category: 'Generative Code', description: 'A nocode tool that generates WordPress blocks and plugins from natural language descriptions.', url: '' },
  { name: 'Rafter', category: 'Generative Code', description: 'A tool to detect and fix vulnerabilities in AI-written code.', url: '' },
  { name: 'Bitrig', category: 'Generative Code', description: 'An iOS app creation tool to build native iPhone apps through natural language prompts.', url: '' },
  { name: 'Letta', category: 'Generative Code', description: 'A platform for building stateful agents with persistent memory and transparent reasoning.', url: '' },
  { name: 'Sculptor', category: 'Generative Code', description: 'An coding assistant that identifies and fixes code issues using multiple isolated agents.', url: '' },
  { name: 'Genpire', category: 'Generative Code', description: 'A tool that generates manufacturing specifications from product concepts.', url: '' },
  { name: 'Zoer', category: 'Generative Code', description: 'A nocode tool to build internal applications and workflows.', url: '' },
  { name: 'VibeScan', category: 'Generative Code', description: 'A tool that scans and fixes vulnerabilities in AI-generated code with security checks and repairs.', url: '' },
  { name: 'Anything', category: 'Generative Code', description: 'A platform that transforms prompts into various digital assets.', url: '' },
  { name: 'Rork', category: 'Generative Code', description: 'A nocode platform that converts text descriptions into mobile apps.', url: '' },
  { name: 'Context.ai', category: 'Generative Code', description: 'A tool to build RAG AI apps using internal knowledge bases.', url: '' },
  { name: 'Amplify Security', category: 'Generative Code', description: 'A tool that detects and fixes code vulnerabilities.', url: '' },
  { name: 'CodeFlash AI', category: 'Generative Code', description: 'A tool to optimize Python code performance while preserving functionality.', url: '' },
  { name: 'Recurse ML', category: 'Generative Code', description: 'A tool that scans pull requests to detect bugs and breaking changes.', url: '' },
  { name: 'Propel', category: 'Generative Code', description: 'An code review assistant that analyzes pull requests to catch issues while learning team coding patterns.', url: '' },
  { name: 'Cubic', category: 'Generative Code', description: 'A tool to review pull requests and enforce coding standards within Github workflows.', url: '' },
  { name: 'VibeFlow', category: 'Generative Code', description: 'A tool to generate full-stack web applications from prompts.', url: '' },
  { name: 'Sita', category: 'Generative Code', description: 'A tool to map codebases and auto-update documentation.', url: '' },
  
  // Text-to-Speech & Voice
  { name: 'ElevenLabs', category: 'Text-To-Speech', description: 'Lifelike text-to-speech and voice cloning.', url: 'https://elevenlabs.io' },
  { name: 'Google Cloud TTS', category: 'Text-To-Speech', description: 'Natural-sounding speech synthesis.', url: 'https://cloud.google.com/text-to-speech' },
  { name: 'Descript', category: 'Text-To-Speech', description: 'Edit audio and video by editing text.', url: 'https://www.descript.com' },
  { name: 'KittenTTS', category: 'Text-To-Speech', description: 'Convert text to speech efficiently.', url: 'https://kittentts.com' },
  { name: 'Fish Audio', category: 'Text-To-Speech', description: 'A platform to generate AI voices from text with customization and voice cloning.', url: '' },
  { name: 'Copilot Audio Expression', category: 'Text-To-Speech', description: 'A tool to convert text into expressive audio narration.', url: '' },
  
  // Podcasting
  { name: 'Wondercraft', category: 'Podcasting', description: 'AI audio studio for podcasts and content.', url: 'https://wondercraft.ai' },
  
  // Speech-to-Text
  { name: 'Whisper', category: 'Speech-To-Text', description: 'OpenAI\'s robust speech recognition model.', url: 'https://openai.com/research/whisper' },
  { name: 'Amical', category: 'Speech-To-Text', description: 'Transcribe meetings and capture voice notes.', url: 'https://amical.ai' },
  { name: 'Otter.ai', category: 'Speech-To-Text', description: 'Real-time transcription and recording.', url: 'https://otter.ai' },
  { name: 'Updaytr', category: 'Speech-To-Text', description: 'A tool to convert voice calls into structured content.', url: '' },
  { name: 'Gladia', category: 'Speech-To-Text', description: 'A tool to convert audio and video into text across multiple languages and insights.', url: '' },
  { name: 'Fluents AI', category: 'Speech-To-Text', description: 'A tool to manage inbound and outbound business calls.', url: '' },
  { name: 'Sluqe', category: 'Speech-To-Text', description: 'A tool that transcribes voice notes and conversations, extracting insights while making content searchable.', url: '' },
  { name: 'Dumai', category: 'Speech-To-Text', description: 'An App that transcribes voice recordings into organized, searchable content with summaries and insights.', url: '' },
  
  // Productivity & Organization
  { name: 'Notion', category: 'Productivity', description: 'All-in-one workspace with integrated AI.', url: 'https://www.notion.so' },
  { name: 'Obsidian', category: 'Productivity', description: 'Personal knowledge management with AI plugins.', url: 'https://obsidian.md' },
  { name: 'Enjo.ai', category: 'Productivity', description: 'Handle support with AI-powered context.', url: 'https://enjo.ai' },
  { name: 'Memara', category: 'Productivity', description: 'AI agents with persistent memory.', url: 'https://memara.ai' },
  { name: 'StatPecker', category: 'Productivity', description: 'Transform data into charts and infographics.', url: 'https://statpecker.com' },
  { name: 'Submind', category: 'Productivity', description: 'Privacy-first note-taking with AI.', url: 'https://submind.ai' },
  { name: 'Chopdi AI', category: 'Productivity', description: 'Note-taking with retrieval and summaries.', url: 'https://chopdi.ai' },
  { name: 'Zapier', category: 'Productivity', description: 'Connect and automate workflows.', url: 'https://zapier.com' },
  { name: 'Quickfix AI', category: 'Productivity', description: 'Context-aware summaries anywhere.', url: 'https://quickfix.ai' },
  { name: 'Cellect', category: 'Productivity', description: 'A tool for spreadsheet data cleanup, extraction, and analysis.', url: 'https://www.cellect.ai/' },
  { name: 'ScreenApp', category: 'Productivity', description: 'A tool that records, transcribes, summarizes, and analyzes audio/video content.', url: 'https://screenapp.io/' },
  { name: 'Cubeo AI', category: 'Productivity', description: 'A nocode platform to build and deploy custom AI Agents using company data.', url: 'https://www.cubeo.ai/' },
  { name: 'Komos AI', category: 'Productivity', description: 'A tool to turn screen demos into automated workflows.', url: '' },
  { name: 'Liminary', category: 'Productivity', description: 'A browser extension that captures, organizes, and recalls information from various sources to find and synthesize insights.', url: '' },
  { name: 'Mem0', category: 'Productivity', description: 'A tool that adds long-term, personalized memory to AI apps and maintain context across sessions.', url: '' },
  { name: 'Supamail', category: 'Productivity', description: 'An MacOS app that summarizes, categorizes, and groups your Gmail emails.', url: '' },
  { name: 'ChatGPT Atlas', category: 'Productivity', description: 'A Browser for MacOS that embeds ChatGPT for assistance, summaries, and automation.', url: '' },
  { name: 'GrapesJS', category: 'Productivity', description: 'A free visual drag-and-drop editor for building web pages and email templates with content creation.', url: '' },
  { name: 'Epsillion', category: 'Productivity', description: 'A tool to automate Excel, Word, and PDF document creation.', url: '' },
  { name: 'Reportly', category: 'Productivity', description: 'A tool and API to create and manage PDF reports from JSON data.', url: '' },
  { name: 'Sparks AI', category: 'Productivity', description: 'A tool to create custom AI agents and collaborative workspaces.', url: '' },
  { name: 'HomeFront', category: 'Productivity', description: 'A CRM platform to manage calls, scheduling, invoicing, and social posts.', url: '' },
  { name: 'Aident AI', category: 'Productivity', description: 'A platform for automating workflows by describing them in plain language.', url: '' },
  { name: 'OmniBox', category: 'Productivity', description: 'A unified interface to search and retrieve information.', url: '' },
  { name: 'Radiant AI', category: 'Productivity', description: 'An MacOS App that captures, summarizes, conversations note-taking and follow-up tasks.', url: '' },
  { name: 'Demodesk', category: 'Productivity', description: 'A platform for remote sales meetings with scheduling, notes, coaching, and live demos.', url: '' },
  { name: 'Recall.ai', category: 'Productivity', description: 'An universal API to capture and process real-time meeting data from major video conferencing platforms.', url: '' },
  { name: 'ResponseHub', category: 'Productivity', description: 'A tool for security questionnaire completion using on compliance paperwork.', url: '' },
  { name: 'CloudAgent', category: 'Productivity', description: 'A platform to automate cloud infrastructure management and security tasks using AI agents.', url: '' },
  { name: 'Quash', category: 'Productivity', description: 'A platform for mobile app testing and QA by generating tests, detecting bugs, and detailed reports.', url: '' },
  { name: 'CloudTalk', category: 'Productivity', description: 'A tool to manage phone interactions using AI voice agents.', url: '' },
  { name: 'viaSocket', category: 'Productivity', description: 'An no-code platform for automating workflows and connecting business apps using a drag-and-drop interface.', url: '' },
  { name: 'Everyday', category: 'Productivity', description: 'A tool to manage tasks, emails, and daily workflows.', url: '' },
  { name: 'Interactico', category: 'Productivity', description: 'A Google Meet add-on for meeting engagement through interactive polls, Q&As, quizzes, and analytics.', url: '' },
  { name: 'Nextbrowser', category: 'Productivity', description: 'A browser that automates web-based workflows and tasks.', url: '' },
  { name: 'Accesstive', category: 'Productivity', description: 'A tool that detects and fixes website accessibility issues without manual coding.', url: '' },
  { name: 'Memory Plugin', category: 'Productivity', description: 'A tool to give AI assistants long-term memory across sessions.', url: '' },
  { name: 'Bika AI', category: 'Productivity', description: 'A no-code platform that creates custom AI assistants for automating various business functions.', url: '' },
  { name: 'Sprinto', category: 'Productivity', description: 'A tool to automate responses for security questionnaires and RFPs.', url: '' },
  { name: 'CursorClip', category: 'Productivity', description: 'A tool that captures, edits, and shares screen recordings with mouse cursor tracking.', url: '' },
  { name: 'EvolveDev', category: 'Productivity', description: 'A tool to analyze engineering workflows and suggest improvements.', url: '' },
  { name: 'myNeutron', category: 'Productivity', description: 'A tool to capture, organize, and query knowledge across platforms.', url: '' },
  { name: 'WorkBeaver', category: 'Productivity', description: 'A tool to automate tasks by learning from your demonstrated workflows.', url: '' },
  { name: 'Zams', category: 'Productivity', description: 'A platform to automate workflows across multiple tools using intelligent agents.', url: '' },
  { name: 'Animant', category: 'Productivity', description: 'An app for iOS and MacOS that creates multimedia slideshows with synchronized 3D models and content organization.', url: '' },
  { name: 'Tenki Cloud', category: 'Productivity', description: 'A tool for self-hosted GitHub Actions runners with automatic scaling capabilities.', url: '' },
  { name: 'GenSpark Browser', category: 'Productivity', description: 'A software to browse, automate tasks, and extract content privately.', url: '' },
  { name: 'Tallyrus', category: 'Productivity', description: 'A tool to evaluate, score, and summarize documents at scale.', url: '' },
  { name: 'Budera', category: 'Productivity', description: 'A tool to manage business growth with AI-driven strategies.', url: '' },
  { name: 'Runable', category: 'Productivity', description: 'A tool to automate digital tasks, research, and content creation.', url: '' },
  { name: 'EmailConnect', category: 'Productivity', description: 'A tool that transforms emails into structured JSON data delivered via webhooks for automated workflows.', url: '' },
  { name: 'HyNote', category: 'Productivity', description: 'A platform with tools for recording, transcribing, and summarizing content from meetings, lectures, and various media formats.', url: '' },
  { name: 'RoboWork', category: 'Productivity', description: 'A tool to build and deploy AI agents, MCP and workflows.', url: '' },
  { name: 'Nonverbia', category: 'Productivity', description: 'A Sales Assistant that analyzes nonverbal communication during virtual meetings to provide real-time coaching for sales representatives.', url: '' },
  { name: 'Activepieces', category: 'Productivity', description: 'A tool to automate workflows and connect apps with AI.', url: '' },
  { name: 'Mastt', category: 'Productivity', description: 'A construction management platform that centralizes project controls with reporting and predictive insights.', url: '' },
  { name: 'Trace', category: 'Productivity', description: 'An calendar app that transforms natural language inputs and screenshots into organized events and tasks with scheduling suggestions.', url: '' },
  { name: 'UX Pilot', category: 'Productivity', description: 'A tool to generate UI/UX designs from text prompts.', url: '' },
  { name: 'HumanLayer', category: 'Productivity', description: 'A tool to add human oversight into automated AI workflows.', url: '' },
  { name: 'Athenic AI', category: 'Productivity', description: 'A tool to query business data and get instant insights.', url: '' },
  { name: 'KUSE AI', category: 'Productivity', description: 'A tool to organize information and create structured collaborative workspaces.', url: '' },
  { name: 'SmythOS', category: 'Productivity', description: 'A no-code platform to build and deploy AI agents through visual drag-and-drop tools.', url: '' },
  { name: 'Yapify', category: 'Productivity', description: 'An email assistant that generates personalized, emails from voice commands by learning your writing style.', url: '' },
  { name: 'Macaron', category: 'Productivity', description: 'An mobile app that creates personalized mini-apps within conversations.', url: '' },
  { name: 'Cobot', category: 'Productivity', description: 'A tool to manage tasks, emails, calendars, and meetings.', url: '' },
  { name: 'Tasker AI', category: 'Productivity', description: 'A tool to execute tasks with digital workflows across applications using natural language commands.', url: '' },
  { name: 'Simular Pro', category: 'Productivity', description: 'An desktop agent that automates workflows across computer.', url: '' },
  { name: 'Functionize', category: 'Productivity', description: 'A tool to automate and manage enterprise software testing workflows.', url: '' },
  { name: 'TicketMine.ai', category: 'Productivity', description: 'A tool that extracts Configuration Item data from IT tickets to maintain CMDB accuracy.', url: '' },
  { name: 'Trails.so', category: 'Productivity', description: 'A tool to create step-by-step guides from recorded processes.', url: '' },
  { name: 'MemU', category: 'Productivity', description: 'A tool to organize and retrieve information for AI applications.', url: '' },
  { name: 'Elvity AI', category: 'Productivity', description: 'A tool to build explainable data pipelines from natural language.', url: '' },
  { name: 'MasterSheets', category: 'Productivity', description: 'A tool that transforms spreadsheets into web applications for business workflows.', url: '' },
  { name: 'VibeDash', category: 'Productivity', description: 'A tool to manage software projects with client collaboration.', url: '' },
  { name: 'FlowMetr', category: 'Productivity', description: 'A tool that monitors open-source AI models in production with real-time analytics, logging and alerting.', url: '' },
  { name: 'Lindra AI', category: 'Productivity', description: 'An virtual employee that automates routine business tasks without coding.', url: '' },
  
  // Marketing & Social Media
  { name: 'Buffer', category: 'Social Media', description: 'Schedule and analyze social media posts.', url: 'https://buffer.com' },
  { name: 'Hootsuite', category: 'Social Media', description: 'Manage multiple social platforms with AI.', url: 'https://www.hootsuite.com' },
  { name: 'Later', category: 'Social Media', description: 'Visual content calendar and scheduling.', url: 'https://www.later.com' },
  { name: 'Thumbler AI', category: 'Social Media', description: 'Generate YouTube thumbnails from prompts.', url: 'https://thumbler.ai' },
  { name: 'PostEverywhere', category: 'Social Media', description: 'Create and publish across platforms.', url: 'https://buffer.com' },
  { name: 'WisePPC', category: 'Marketing', description: 'Optimize Amazon advertising campaigns.', url: 'https://wiseppc.ai' },
  { name: 'Profound', category: 'Marketing', description: 'Monitor brand in AI search results.', url: 'https://profound.ai' },
  { name: 'Picky Assist', category: 'Marketing', description: 'Multi-channel communication management.', url: 'https://www.activecampaign.com' },
  { name: 'dynares', category: 'Marketing', description: 'Generate personalized landing pages.', url: 'https://www.unbounce.com' },
  { name: 'BrightStage AI', category: 'Marketing', description: 'Manage sales presentations and webinars.', url: 'https://www.sales.com' },
  { name: 'Vyrill', category: 'Social Media', description: 'A tool that analyzes and organizes UGC videos and insights for e-commerce brands.', url: '' },
  { name: 'Flowcart AI', category: 'Marketing', description: 'A tool to manage sales and marketing through WhatsApp chat.', url: '' },
  { name: 'Jarts', category: 'Marketing', description: 'A platform that tracks and improves your brand’s visibility in AI-generated search results.', url: '' },
  { name: 'Toffu AI', category: 'Marketing', description: 'A marketing automation platform that manages campaigns, creates content, analyzes data through a chat interface.', url: '' },
  { name: 'HiClip', category: 'Social Media', description: 'A tool that creates short, highlight clips from long-form videos.', url: '' },
  { name: 'Amplifiles', category: 'Marketing', description: 'A tool that transforms real estate photos into videos with voice-overs, captions, and branding.', url: '' },
  { name: 'FeedGuardians', category: 'Social Media', description: 'A tool that manages social media comment responses for e-commerce brands.', url: '' },
  { name: 'Trackboxx', category: 'Marketing', description: 'A platform for cookie-free web analytics and insights for website performance and conversions.', url: '' },
  { name: 'BidVentor', category: 'Marketing', description: 'A tool that optimizes Amazon ad campaigns.', url: '' },
  { name: 'DealerAI', category: 'Marketing', description: 'A platform for car dealership operations with conversational agents integrations.', url: '' },
  { name: 'Potions', category: 'Marketing', description: 'A tool to create and manage automated AI newsletters.', url: '' },
  { name: 'Experimently', category: 'Marketing', description: 'A tool to create and test landing pages.', url: '' },
  { name: 'Mapster', category: 'Marketing', description: 'A tool to measure and improve product-market fit with surveys.', url: '' },
  { name: 'Nrev AI', category: 'Marketing', description: 'A tool to automate go-to-market workflows and revenue operations.', url: '' },
  { name: 'RMIQ', category: 'Marketing', description: 'A platform that optimizes retail media ad campaigns across multiple networks through a unified dashboard.', url: '' },
  { name: 'Vaizle', category: 'Marketing', description: 'A tool to analyze Meta Ads and generate campaign insights.', url: '' },
  { name: 'Skippership', category: 'Marketing', description: 'A tool to analyze visitor behavior and identify conversion obstacles and insights.', url: '' },
  { name: 'Quiki.io', category: 'Social Media', description: 'A tool to search, summarize, and analyze saved social videos.', url: '' },
  { name: 'WebTracker AI', category: 'Marketing', description: 'A tool to monitor competitors’ websites, pricing, and market trends with insights.', url: '' },
  { name: 'Archive', category: 'Social Media', description: 'A tool for influencer marketing to track, organize, and manage user-generated content.', url: '' },
  { name: 'Stormy AI', category: 'Social Media', description: 'A tool for influencer marketing campaigns from creator discovery to performance tracking.', url: '' },
  { name: 'Lorean Labs', category: 'Marketing', description: 'A tool to generate video ads from product images and scripts.', url: '' },
  { name: 'Tenali', category: 'Marketing', description: 'An sales assistant for real-time support during calls by answering product questions, note-taking, and updating CRM records.', url: '' },
  { name: 'Amplifa', category: 'Marketing', description: 'A platform to automate B2B lead generation and sales outreach.', url: '' },
  
  // Inspiration
  { name: 'Canva', category: 'Inspiration', description: 'Design platform with AI-powered features.', url: 'https://www.canva.com' },
  { name: 'AI HomeDesign', category: 'Inspiration', description: 'Interior design concepts from photos.', url: 'https://aihomedesign.com' },
  { name: 'Figma AI', category: 'Inspiration', description: 'Design tools with AI assistance.', url: 'https://www.figma.com' },
  { name: 'ShootSolo', category: 'Inspiration', description: 'An app to record videos hands-free using voice commands.', url: '' },
  
  // Translation & Localization
  { name: 'Perso.ai', category: 'Translation', description: 'Translate and lip-sync videos globally.', url: 'https://perso.ai' },
  { name: 'Google Translate', category: 'Translation', description: 'AI-powered translation for 100+ languages.', url: 'https://translate.google.com' },
  { name: 'DeepL', category: 'Translation', description: 'High-quality neural machine translation.', url: 'https://www.deepl.com' },
  { name: 'Luboo', category: 'Translation', description: 'A tool to translate and dub short videos in multiple languages.', url: '' },
  { name: 'Cavya AI', category: 'Translation', description: 'A tool for translation preparation by generating glossaries and style guides for content localization.', url: '' },
  
  // Research & Analysis
  { name: 'Semantic Scholar', category: 'Research', description: 'AI-powered research paper search.', url: 'https://www.semanticscholar.org' },
  { name: 'Company Research Agent', category: 'Research', description: 'Analyze company data for reports.', url: 'https://www.perplexity.ai' },
  { name: 'Elicit', category: 'Research', description: 'AI research assistant for literature.', url: 'https://elicit.org' },
  { name: 'Crunchbase', category: 'Research', description: 'A platform that provides real-time business data and insights on companies, investors, and market trends.', url: '' },
  { name: 'Extend AI', category: 'Research', description: 'A platform that converts unstructured documents into structured data with customizable APIs.', url: '' },
  { name: 'Noah AI', category: 'Research', description: 'A platform for literature reviews, data extraction, and scientific analysis to research for life science.', url: '' },
  { name: 'PageLM', category: 'Research', description: 'An open-source version of Google\'s NotebookLM.', url: '' },
  { name: 'Hyperlink by Nexa', category: 'Research', description: 'A tool to search, summarize, and answer from offline documents.', url: '' },
  { name: 'Spatial Agents', category: 'Research', description: 'A platform for geospatial data analysis through conversational interfaces.', url: '' },
  { name: 'SparkToro', category: 'Research', description: 'A research platform to discover audience behaviors, interests, and online influence.', url: '' },
  { name: 'Capix', category: 'Research', description: 'A platform to find and analyze private companies through natural language search.', url: '' },
  { name: 'Pline', category: 'Research', description: 'A platform that extracts structured data from websites without coding.', url: '' },
  { name: 'Sinthax AI', category: 'Research', description: 'A tool to collect and organize feedback through conversations.', url: '' },
  { name: 'SEAL Leaderboard', category: 'Research', description: 'A tool to evaluate and rank large language models.', url: '' },
  { name: 'Dr7.ai', category: 'Research', description: 'A platform that analyzes medical data and generates clinical content through text and image analysis.', url: '' },
  { name: 'Futurwise', category: 'Research', description: 'A tool to summarize articles, videos, PDFs, and bookmarks.', url: '' },
  { name: 'Drivetrain', category: 'Research', description: 'A platform for financial planning and analysis by generating models from business data and conversational analytics.', url: '' },
  { name: 'ReportCraft', category: 'Research', description: 'A tool to generate business reports from prompts.', url: '' },
  { name: 'Maskara AI', category: 'Research', description: 'A platform to conduct live debates between AI models to deliver the best answers without complex prompts.', url: '' },
  { name: 'IdeaBoard', category: 'Research', description: 'A platform with whiteboards that generates custom templates for collaborative brainstorming and planning from prompts.', url: '' },
  { name: 'Gatsbi', category: 'Research', description: 'A platform that generates and assists with research papers, literature reviews, and patent documents.', url: '' },
  
  // Finance & Business
  { name: 'Endex', category: 'Finance', description: 'Financial data analysis in Excel.', url: 'https://endex.ai' },
  { name: 'Alpaca', category: 'Finance', description: 'AI-powered trading and portfolio analysis.', url: 'https://alpaca.markets' },
  { name: 'SignalsHQ', category: 'Finance', description: 'A tool for CPA firms to extract data, research regulations, and generate working papers.', url: '' },
  { name: 'Riskova', category: 'Finance', description: 'A platform that automates risk assessment, monitoring, and mitigation.', url: '' },
  { name: 'Receiptor AI', category: 'Finance', description: 'A platform that extracts, organizes, and categorizes financial data from receipts across multiple sources for accounting integration.', url: '' },
  { name: 'Noesent', category: 'Finance', description: 'A tool to automate fintech tasks like payments and fraud detection.', url: '' },
  
  // Automation & Workflow
  { name: 'Make', category: 'Automation & Agents', description: 'Visual workflow automation platform.', url: 'https://www.make.com' },
  { name: 'Retool', category: 'Automation & Agents', description: 'Build internal tools fast.', url: 'https://www.retool.com' },
  { name: 'Klavis AI', category: 'Automation & Agents', description: 'Connect AI agents with MCP.', url: 'https://www.make.com' },
  { name: 'Yorph AI', category: 'Automation & Agents', description: 'No-code data analysis pipelines.', url: 'https://www.retool.com' },
  { name: 'GPTBots.ai', category: 'Automation & Agents', description: 'Build enterprise no-code agents.', url: 'https://www.gptbots.ai' },
  { name: 'Agenta', category: 'Automation & Agents', description: 'Open source LLM app platform.', url: 'https://agenta.ai' },
  { name: 'MemMachine', category: 'Automation & Agents', description: 'Persistent memory for AI agents.', url: 'https://github.com/lgrammel/ai' },
  { name: 'Kento', category: 'Automation & Agents', description: 'Cache queries to cut costs.', url: 'https://www.anthropic.com' },
  { name: 'iGPT', category: 'Automation & Agents', description: 'Convert emails to structured data.', url: 'https://www.zapier.com' },
  { name: 'Cekura', category: 'Automation & Agents', description: 'Test conversational AI quality.', url: 'https://www.promptquality.com' },
  { name: 'AgentKit (OpenAI)', category: 'Automation & Agents', description: 'AgentKit enables users to visually create and manage AI-powered agent workflows without coding.', url: '' },
  
  // Avatar & Video
  { name: 'Ziddny', category: 'Avatar', description: 'Create customizable AI avatars.', url: 'https://ziddny.com' },
  { name: 'Keevx', category: 'Avatar', description: 'Create multilingual avatar videos.', url: 'https://keevx.com' },
  { name: 'Soul Machines', category: 'Avatar', description: 'Build lifelike digital humans.', url: 'https://www.soulmachines.com' },
  { name: 'Jogg AI', category: 'Avatar', description: 'A tool to create avatar-based videos from text or photos.', url: '' },
  
  // Detection & Security
  { name: 'Polygraf AI', category: 'AI Detection', description: 'Detect AI-generated text.', url: 'https://polygraf.ai' },
  { name: 'Originality.AI', category: 'AI Detection', description: 'Detect AI content and plagiarism.', url: 'https://originality.ai' },
  
  // Design & Inspiration
  
  // Gaming
  { name: 'Dreamcore', category: 'Gaming', description: 'Create mobile games from text.', url: 'https://dreamcore.ai' },
  { name: 'Unreal Engine', category: 'Gaming', description: 'Game engine with AI features.', url: 'https://www.unrealengine.com' },
  { name: 'Matrix Game 2.0', category: 'Gaming', description: 'A tool to generate interactive real-time video in virtual environments with keyboard-controlled characters and cameras.', url: '' },
  
  // Self-Improvement & Learning
  { name: 'DailyMe Journal', category: 'Self-Improvement', description: 'Analyze emotional patterns.', url: 'https://dailyme.app' },
  { name: 'MasterClass', category: 'Self-Improvement', description: 'Learn from experts with AI recommendations.', url: 'https://www.masterclass.com' },
  { name: 'Skillduck', category: 'Self-Improvement', description: 'A tool for creating, customizing, and translating interactive online training courses.', url: '' },
  { name: 'Arist', category: 'Self-Improvement', description: 'A tool to convert documents into personalized microlearning courses delivered via messaging apps.', url: '' },
  { name: 'Resyfy AI', category: 'Self-Improvement', description: 'A tool to organize, verify, and optimize career achievements into digital resumes and portfolios.', url: '' },
  { name: 'Blobu', category: 'Self-Improvement', description: 'A tool to create and explore book summaries and mashups.', url: '' },
  { name: 'Oboe', category: 'Self-Improvement', description: 'A tool to create personalized educational courses from prompts.', url: '' },
  
  // Aggregators
  { name: 'CometAPI', category: 'Aggregators', description: 'Access 500+ AI models via API.', url: 'https://cometapi.com' },
  { name: 'Hugging Face', category: 'Aggregators', description: 'Hub for machine learning models.', url: 'https://huggingface.co' },
  { name: 'Geekflare AI', category: 'Aggregators', description: 'A platform that consolidates multiple AI models into one collaborative workspace.', url: '' },
  { name: 'nexos.ai', category: 'Aggregators', description: 'An AI Orchestration Platform that centralizes access to multiple language models, routes queries and optimizes costs.', url: '' },
  { name: 'Social Walls by Taggbox', category: 'Aggregators', description: 'A platform that aggregates social media content onto customizable digital displays for events and websites.', url: '' },
  { name: 'Informed', category: 'Aggregators', description: 'A tool to aggregate news and narrate it as podcasts.', url: '' },
  
  // Prompt Management
  { name: 'Versuno AI', category: 'Prompt Guides', description: 'Organize and optimize prompts.', url: 'https://www.promptflow.microsoft.com' },
  { name: 'PromptBase', category: 'Prompt Guides', description: 'Marketplace for AI prompts.', url: 'https://www.promptbase.com' },
  { name: 'Evaligo', category: 'Prompt Guides', description: 'A tool to test, optimize, and manage prompts with feedback, analytics, and collaboration tools.', url: '' },
  { name: 'Prompt Sloth', category: 'Prompt Guides', description: 'A Chrome extension to turn simple AI requests into detailed prompts.', url: '' },
  { name: 'Modeltion', category: 'Prompt Guides', description: 'A tool to build and test AI workflows with prompts, images and APIs.', url: '' },
  { name: 'Empromptu.ai', category: 'Prompt Guides', description: 'A tool to create, manage, share and optimize prompts through templates and collaboration.', url: '' },
  
  // Additional Popular Tools (from original list)
  { name: 'RightNow AI', category: 'Generative Code', description: 'AI CUDA code editor.', url: 'https://github.com' },

  // --- NEW TOOLS FROM TEXT LIST ---
  // Note: url: '' is a placeholder and needs to be filled in.
  // Tools with multiple categories were assigned the first one listed.
  
  { name: 'Vyrill', category: 'Social Media', description: 'A tool that analyzes and organizes UGC videos and insights for e-commerce brands.', url: '' },
  { name: 'Crunchbase', category: 'Finance', description: 'A platform that provides real-time business data and insights on companies, investors, and market trends.', url: '' },
  { name: 'Skillduck', category: 'Self-Improvement', description: 'A tool for creating, customizing, and translating interactive online training courses.', url: '' },
  { name: 'Cellect', category: 'Productivity', description: 'A tool for spreadsheet data cleanup, extraction, and analysis.', url: '' },
  { name: 'Flowcart AI', category: 'Marketing', description: 'A tool to manage sales and marketing through WhatsApp chat.', url: '' },
  { name: 'ScreenApp', category: 'Productivity', description: 'A tool that records, transcribes, summarizes, and analyzes audio/video content.', url: '' },
  { name: 'Cubeo AI', category: 'Productivity', description: 'A nocode platform to build and deploy custom AI assistants using company data.', url: '' },
  { name: 'Google Veo', category: 'Generative Video', description: 'Google Veo 3 generates realistic, cinematic videos with audio from text or image prompts.', url: '' },
  { name: 'AgentKit (OpenAI)', category: 'Automation & Agents', description: 'AgentKit enables users to visually create and manage AI-powered agent workflows without coding.', url: '' },
  { name: 'Cursor v2', category: 'Generative Code', description: 'Cursor is an AI-powered code editor that helps engineers build software faster.', url: '' },
  { name: 'IntoChat', category: 'Chat', description: 'A chatbot platform for customer support, lead generation, and engagement across multiple channels.', url: '' },
  { name: 'Komos AI', category: 'Productivity', description: 'A tool to turn screen demos into automated workflows.', url: '' },
  { name: 'NotebookLM', category: 'Productivity', description: 'Chat with your documents and websites.', url: '' },
  { name: 'Liminary', category: 'Productivity', description: 'A browser extension that captures, organizes, and recalls information from various sources to find and synthesize insights.', url: '' },
  { name: 'Mem0', category: 'Productivity', description: 'A tool that adds long-term, personalized memory to AI apps and maintain context across sessions.', url: '' },
  { name: 'Supamail', category: 'Productivity', description: 'An MacOS app that summarizes, categorizes, and groups your Gmail emails.', url: '' },
  { name: 'ChatGPT Atlas', category: 'Productivity', description: 'A Browser for MacOS that embeds ChatGPT for assistance, summaries, and automation.', url: '' },
  { name: 'Jarts', category: 'Marketing', description: 'A platform that tracks and improves your brand’s visibility in AI-generated search results.', url: '' },
  { name: 'GrapesJS', category: 'Productivity', description: 'A free visual drag-and-drop editor for building web pages and email templates with content creation.', url: '' },
  { name: 'Toffu AI', category: 'Marketing', description: 'A marketing automation platform that manages campaigns, creates content, analyzes data through a chat interface.', url: '' },
  { name: 'Writitude', category: 'Copywriting', description: 'A tool to create and enforce custom writing guidelines with analysis for consistent brand voice.', url: '' },
  { name: 'Epsillion', category: 'Productivity', description: 'A tool to automate Excel, Word, and PDF document creation.', url: '' },
  { name: 'Extend AI', category: 'Research', description: 'A platform that converts unstructured documents into structured data with customizable APIs.', url: '' },
  { name: 'HiClip', category: 'Social Media', description: 'A tool that creates short, highlight clips from long-form videos.', url: '' },
  { name: 'Reportly', category: 'Productivity', description: 'A tool and API to create and manage PDF reports from JSON data.', url: '' },
  { name: 'Sparks AI', category: 'Productivity', description: 'A tool to create custom AI agents and collaborative workspaces.', url: '' },
  { name: 'Sonura Studio', category: 'Music', description: 'A tool to generate music, beats, and sound effects.', url: '' },
  { name: 'Jogg AI', category: 'Avatar', description: 'A tool to create avatar-based videos from text or photos.', url: '' },
  { name: 'HomeFront', category: 'Productivity', description: 'A CRM platform to manage calls, scheduling, invoicing, and social posts.', url: '' },
  { name: 'ShortMotion', category: 'Motion Capture', description: 'An iOS app for creating and editing stop motion animations.', url: '' },
  { name: 'Loman AI', category: 'Voice Modulation', description: 'An AI voice phone agent for restaurants that answers calls, takes orders and reservations.', url: '' },
  { name: 'Noah AI', category: 'Research', description: 'A platform for literature reviews, data extraction, and scientific analysis to research for life science.', url: '' },
  { name: 'Fish Audio', category: 'Text-To-Speech', description: 'A platform to generate AI voices from text with customization and voice cloning.', url: '' },
  { name: 'Aident AI', category: 'Productivity', description: 'A platform for automating workflows by describing them in plain language.', url: '' },
  { name: 'OmniBox', category: 'Productivity', description: 'A unified interface to search and retrieve information.', url: '' },
  { name: 'PageLM', category: 'Research', description: 'An open-source version of Google\'s NotebookLM.', url: '' },
  { name: 'Radiant AI', category: 'Productivity', description: 'An MacOS App that captures, summarizes, conversations note-taking and follow-up tasks.', url: '' },
  { name: 'Bloom Studio', category: 'Generative Video', description: 'A tool to generate product photos and videos for e-commerce.', url: '' },
  { name: 'Tight Studio', category: 'Video Editing', description: 'A MacOS Software to create product demo and tutorial videos with auto-zoom, captions, and voiceovers.', url: '' },
  { name: 'Demodesk', category: 'Productivity', description: 'A platform for remote sales meetings with scheduling, notes, coaching, and live demos.', url: '' },
  { name: 'Anpo AI', category: 'Generative Video', description: 'A tool to turn product photos into lifestyle videos.', url: '' },
  { name: 'Arist', category: 'Self-Improvement', description: 'A tool to convert documents into personalized microlearning courses delivered via messaging apps.', url: '' },
  { name: 'RoboMonkey', category: 'Generative Code', description: 'A nocode tool to create custom Chrome extensions and browser automations.', url: '' },
  { name: 'Recall.ai', category: 'Productivity', description: 'An universal API to capture and process real-time meeting data from major video conferencing platforms.', url: '' },
  { name: 'ResponseHub', category: 'Productivity', description: 'A tool for security questionnaire completion using on compliance paperwork.', url: '' },
  { name: 'Amplifiles', category: 'Marketing', description: 'A tool that transforms real estate photos into videos with voice-overs, captions, and branding.', url: '' },
  { name: 'Decor8 AI', category: 'Generative Art', description: 'A tool to generate interior redesigns from room photos.', url: '' },
  { name: 'FeedGuardians', category: 'Social Media', description: 'A tool that manages social media comment responses for e-commerce brands.', url: '' },
  { name: 'Tutorial AI', category: 'Generative Video', description: 'A platform that creates step-by-step guides and demo videos.', url: '' },
  { name: 'Resyfy AI', category: 'Self-Improvement', description: 'A tool to organize, verify, and optimize career achievements into digital resumes and portfolios.', url: '' },
  { name: 'Evaligo', category: 'Prompt Guides', description: 'A tool to test, optimize, and manage prompts with feedback, analytics, and collaboration tools.', url: '' },
  { name: 'Floot', category: 'Generative Code', description: 'A platform to build web apps by describing your ideas to an AI chat.', url: '' },
  { name: 'Updaytr', category: 'Speech-To-Text', description: 'A tool to convert voice calls into structured content.', url: '' },
  { name: 'Luboo', category: 'Translation', description: 'A tool to translate and dub short videos in multiple languages.', url: '' },
  { name: 'CloudAgent', category: 'Productivity', description: 'A platform to automate cloud infrastructure management and security tasks using AI agents.', url: '' },
  { name: 'Trackboxx', category: 'Marketing', description: 'A platform for cookie-free web analytics and insights for website performance and conversions.', url: '' },
  { name: 'Image MetaHub', category: 'Image Improvement', description: 'A tool to organize and search AI-generated images locally.', url: '' },
  { name: 'Quash', category: 'Productivity', description: 'A platform for mobile app testing and QA by generating tests, detecting bugs, and detailed reports.', url: '' },
  { name: 'BidVentor', category: 'Marketing', description: 'A tool that optimizes Amazon ad campaigns.', url: '' },
  { name: 'CloudTalk', category: 'Productivity', description: 'A tool to manage phone interactions using AI voice agents.', url: '' },
  { name: 'DealerAI', category: 'Marketing', description: 'A platform for car dealership operations with conversational agents integrations.', url: '' },
  { name: 'Potions', category: 'Marketing', description: 'A tool to create and manage automated AI newsletters.', url: '' },
  { name: 'Gatsbi', category: 'Research', description: 'A platform that generates and assists with research papers, literature reviews, and patent documents.', url: '' },
  { name: 'Experimently', category: 'Marketing', description: 'A tool to create and test landing pages.', url: '' },
  { name: 'Sonant', category: 'Chat', description: 'An AI receptionist for insurance agencies phone calls tasks.', url: '' },
  { name: 'Maastr', category: 'Music', description: 'A tool to master audio tracks with collaboration tools.', url: '' },
  { name: 'AeroChat', category: 'Chat', description: 'A tool that unifies customer communication across channels for brand-consistent support.', url: '' },
  { name: 'Sinthax AI', category: 'Research', description: 'A tool to collect and organize feedback through conversations.', url: '' },
  { name: 'Prompt Sloth', category: 'Prompt Guides', description: 'A Chrome extension to turn simple AI requests into detailed prompts.', url: '' },
  { name: 'viaSocket', category: 'Productivity', description: 'An no-code platform for automating workflows and connecting business apps using a drag-and-drop interface.', url: '' },
  { name: 'Sculptor', category: 'Generative Code', description: 'An coding assistant that identifies and fixes code issues using multiple isolated agents.', url: '' },
  { name: 'Everyday', category: 'Productivity', description: 'A tool to manage tasks, emails, and daily workflows.', url: '' },
  { name: 'Interactico', category: 'Productivity', description: 'A Google Meet add-on for meeting engagement through interactive polls, Q&As, quizzes, and analytics.', url: '' },
  { name: 'Sora App', category: 'Generative Video', description: 'An iOS App that generates videos from text descriptions.', url: '' },
  { name: 'Genpire', category: 'Generative Code', description: 'A tool that generates manufacturing specifications from product concepts.', url: '' },
  { name: 'Nextbrowser', category: 'Productivity', description: 'A browser that automates web-based workflows and tasks.', url: '' },
  { name: 'Cavya AI', category: 'Translation', description: 'A tool for translation preparation by generating glossaries and style guides for content localization.', url: '' },
  { name: 'Accesstive', category: 'Productivity', description: 'A tool that detects and fixes website accessibility issues without manual coding.', url: '' },
  { name: 'Form3D', category: 'Generative Art', description: 'A tool to convert online furniture links into SketchUp 3D models.', url: '' },
  { name: 'SVGMaker', category: 'Generative Art', description: 'A tool that converts text descriptions into editable vector graphics.', url: '' },
  { name: 'Blobu', category: 'Self-Improvement', description: 'A tool to create and explore book summaries and mashups.', url: '' },
  { name: 'HelpLoom', category: 'Chat', description: 'A tool to provide live chat and customer support.', url: '' },
  { name: 'Modeltion', category: 'Prompt Guides', description: 'A tool to build and test AI workflows with prompts, images and APIs.', url: '' },
  { name: 'Memory Plugin', category: 'Productivity', description: 'A tool to give AI assistants long-term memory across sessions.', url: '' },
  { name: 'Bika AI', category: 'Productivity', description: 'A no-code platform that creates custom AI assistants for automating various business functions.', url: '' },
  { name: 'VoiceDrop', category: 'Voice Modulation', description: 'A tool that creates and delivers personalized ringless voicemails using voice cloning.', url: '' },
  { name: 'Tapybl', category: 'Generative Video', description: 'A tool that transforms documents into interactive video lessons with quizzes.', url: '' },
  { name: 'Sprinto', category: 'Productivity', description: 'A tool to automate responses for security questionnaires and RFPs.', url: '' },
  { name: 'CursorClip', category: 'Productivity', description: 'A tool that captures, edits, and shares screen recordings with mouse cursor tracking.', url: '' },
  { name: 'EvolveDev', category: 'Productivity', description: 'A tool to analyze engineering workflows and suggest improvements.', url: '' },
  { name: 'Rounded', category: 'Voice Modulation', description: 'An AI voice platform that automates phone interactions through customizable virtual assistants.', url: '' },
  { name: 'SEAL Leaderboard', category: 'Research', description: 'A tool to evaluate and rank large language models.', url: '' },
  { name: 'Propel', category: 'Generative Code', description: 'An code review assistant that analyzes pull requests to catch issues while learning team coding patterns.', url: '' },
  { name: 'GrainODM', category: 'Image Scanning', description: 'A tool to automate grain analysis with rapid testing.', url: '' },
  { name: 'myNeutron', category: 'Productivity', description: 'A tool to capture, organize, and query knowledge across platforms.', url: '' },
  { name: 'WorkBeaver', category: 'Productivity', description: 'A tool to automate tasks by learning from your demonstrated workflows.', url: '' },
  { name: 'Geekflare AI', category: 'Aggregators', description: 'A platform that consolidates multiple AI models into one collaborative workspace.', url: '' },
  { name: 'Heyy', category: 'Chat', description: 'A tool for creating customer conversations across messaging platforms using AI agents for sales, marketing, and support.', url: '' },
  { name: 'Zams', category: 'Productivity', description: 'A platform to automate workflows across multiple tools using intelligent agents.', url: '' },
  { name: 'Mapster', category: 'Marketing', description: 'A tool to measure and improve product-market fit with surveys.', url: '' },
  { name: 'Animant', category: 'Productivity', description: 'An app for iOS and MacOS that creates multimedia slideshows with synchronized 3D models and content organization.', url: '' },
  { name: 'Dyad', category: 'Generative Code', description: 'An open-source tool to build full-stack apps from natural language.', url: '' },
  { name: 'Hyperlink by Nexa', category: 'Research', description: 'A tool to search, summarize, and answer from offline documents.', url: '' },
  { name: 'Nrev AI', category: 'Marketing', description: 'A tool to automate go-to-market workflows and revenue operations.', url: '' },
  { name: 'Crossfade', category: 'Video Editing', description: 'An video editor to transcribe, highlight, and extract key video segments.', url: '' },
  { name: 'SignalsHQ', category: 'Finance', description: 'A tool for CPA firms to extract data, research regulations, and generate working papers.', url: '' },
  { name: 'Lamatic', category: 'Generative Code', description: 'A tool to build and deploy generative AI applications visually.', url: '' },
  { name: 'Gladia', category: 'Speech-To-Text', description: 'A tool to convert audio and video into text across multiple languages and insights.', url: '' },
  { name: 'Tenki Cloud', category: 'Productivity', description: 'A tool for self-hosted GitHub Actions runners with automatic scaling capabilities.', url: '' },
  { name: 'Cloudonix', category: 'Voice Modulation', description: 'A tool to integrate AI voice communication for businesses.', url: '' },
  { name: 'TestDriver AI', category: 'Generative Code', description: 'A tool to automate software testing across platforms using AI vision.', url: '' },
  { name: 'ShootSolo', category: 'Inspiration', description: 'An app to record videos hands-free using voice commands.', url: '' },
  { name: 'GenSpark Browser', category: 'Productivity', description: 'A software to browse, automate tasks, and extract content privately.', url: '' },
  { name: 'Tallyrus', category: 'Productivity', description: 'A tool to evaluate, score, and summarize documents at scale.', url: '' },
  { name: 'Budera', category: 'Productivity', description: 'A tool to manage business growth with AI-driven strategies.', url: '' },
  { name: 'Unshift AI', category: 'Generative Code', description: 'A visual website builder that converts designs into code and content generation.', url: '' },
  { name: 'Capix', category: 'Research', description: 'A platform to find and analyze private companies through natural language search.', url: '' },
  { name: 'Morphic', category: 'Generative Video', description: 'A tool to generate and edit images, videos, and scenes.', url: '' },
  { name: 'Pline', category: 'Research', description: 'A platform that extracts structured data from websites without coding.', url: '' },
  { name: 'Oboe', category: 'Self-Improvement', description: 'A tool to create personalized educational courses from prompts.', url: '' },
  { name: 'Runable', category: 'Productivity', description: 'A tool to automate digital tasks, research, and content creation.', url: '' },
  { name: 'EmailConnect', category: 'Productivity', description: 'A tool that transforms emails into structured JSON data delivered via webhooks for automated workflows.', url: '' },
  { name: 'NeuralTalk AI', category: 'Chat', description: 'A tool to create custom, knowledge-based chatbots that automatically updates with business content.', url: '' },
  { name: 'RMIQ', category: 'Marketing', description: 'A platform that optimizes retail media ad campaigns across multiple networks through a unified dashboard.', url: '' },
  { name: 'Fluents AI', category: 'Speech-To-Text', description: 'A tool to manage inbound and outbound business calls.', url: '' },
  { name: 'HyNote', category: 'Productivity', description: 'A platform with tools for recording, transcribing, and summarizing content from meetings, lectures, and various media formats.', url: '' },
  { name: 'Riskova', category: 'Finance', description: 'A platform that automates risk assessment, monitoring, and mitigation.', url: '' },
  { name: 'DrawMingo', category: 'Generative Video', description: 'A tool that transforms hand-drawn artwork into animated videos with music and effects.', url: '' },
  { name: 'RoboWork', category: 'Productivity', description: 'A tool to build and deploy AI agents, MCP and workflows.', url: '' },
  { name: 'Sita', category: 'Generative Code', description: 'A tool to map codebases and auto-update documentation.', url: '' },
  { name: 'Vaizle', category: 'Marketing', description: 'A tool to analyze Meta Ads and generate campaign insights.', url: '' },
  { name: 'Figmentor', category: 'Generative Code', description: 'A tool that converts Figma designs into Elementor WordPress templates.', url: '' },
  { name: 'Sluqe', category: 'Speech-To-Text', description: 'A tool that transcribes voice notes and conversations, extracting insights while making content searchable.', url: '' },
  { name: 'Spatial Agents', category: 'Research', description: 'A platform for geospatial data analysis through conversational interfaces.', url: '' },
  { name: 'Skippership', category: 'Marketing', description: 'A tool to analyze visitor behavior and identify conversion obstacles and insights.', url: '' },
  { name: 'Nonverbia', category: 'Productivity', description: 'A Sales Assistant that analyzes nonverbal communication during virtual meetings to provide real-time coaching for sales representatives.', url: '' },
  { name: 'nexos.ai', category: 'Aggregators', description: 'An AI Orchestration Platform that centralizes access to multiple language models, routes queries and optimizes costs.', url: '' },
  { name: 'Vidvoi', category: 'Video Editing', description: 'A tool to add voiceovers and captions to videos.', url: '' },
  { name: 'Activepieces', category: 'Productivity', description: 'A tool to automate workflows and connect apps with AI.', url: '' },
  { name: 'Dumai', category: 'Speech-To-Text', description: 'An App that transcribes voice recordings into organized, searchable content with summaries and insights.', url: '' },
  { name: 'Receiptor AI', category: 'Finance', description: 'A platform that extracts, organizes, and categorizes financial data from receipts across multiple sources for accounting integration.', url: '' },
  { name: 'Telex', category: 'Generative Code', description: 'A nocode tool that generates WordPress blocks and plugins from natural language descriptions.', url: '' },
  { name: 'Rafter', category: 'Generative Code', description: 'A tool to detect and fix vulnerabilities in AI-written code.', url: '' },
  { name: 'Symvol', category: 'Generative Video', description: 'A tool to convert written articles into video content.', url: '' },
  { name: 'Social Walls by Taggbox', category: 'Aggregators', description: 'A platform that aggregates social media content onto customizable digital displays for events and websites.', url: '' },
  { name: 'Quiki.io', category: 'Social Media', description: 'A tool to search, summarize, and analyze saved social videos.', url: '' },
  { name: 'Mastt', category: 'Productivity', description: 'A construction management platform that centralizes project controls with reporting and predictive insights.', url: '' },
  { name: 'Copilot Audio Expression', category: 'Text-To-Speech', description: 'A tool to convert text into expressive audio narration.', url: '' },
  { name: 'Sync.so', category: 'Generative Video', description: 'A tool to sync lips and clone voices in videos.', url: '' },
  { name: 'Bitrig', category: 'Generative Code', description: 'An iOS app creation tool to build native iPhone apps through natural language prompts.', url: '' },
  { name: 'Letta', category: 'Generative Code', description: 'A platform for building stateful agents with persistent memory and transparent reasoning.', url: '' },
  { name: 'Trace', category: 'Productivity', description: 'An calendar app that transforms natural language inputs and screenshots into organized events and tasks with scheduling suggestions.', url: '' },
  { name: 'UX Pilot', category: 'Productivity', description: 'A tool to generate UI/UX designs from text prompts.', url: '' },
  { name: 'Montra', category: 'Generative Art', description: 'A tool to generate images and create multi-scene videos.', url: '' },
  { name: 'HumanLayer', category: 'Productivity', description: 'A tool to add human-in-the-loop oversight into automated AI workflows.', url: '' },
  { name: 'SparkToro', category: 'Research', description: 'A research platform to discover audience behaviors, interests, and online influence.', url: '' },
  { name: 'Cubic', category: 'Generative Code', description: 'A tool to review pull requests and enforce coding standards within Github workflows.', url: '' },
  { name: 'Informed', category: 'Aggregators', description: 'A tool to aggregate news and narrate it as podcasts.', url: '' },
  { name: 'VibeFlow', category: 'Generative Code', description: 'A tool to generate full-stack web applications from prompts.', url: '' },
  { name: 'Dr7.ai', category: 'Research', description: 'A platform that analyzes medical data and generates clinical content through text and image analysis.', url: '' },
  { name: 'Zenor.ai', category: 'Chat', description: 'A tool to assist shopify shopping with chat, voice, and video.', url: '' },
  { name: 'Athenic AI', category: 'Productivity', description: 'A tool to query business data and get instant insights.', url: '' },
  { name: 'Noesent', category: 'Finance', description: 'A tool to automate fintech tasks like payments and fraud detection.', url: '' },
  { name: 'Futurwise', category: 'Research', description: 'A tool to summarize articles, videos, PDFs, and bookmarks.', url: '' },
  { name: 'Drivetrain', category: 'Research', description: 'A platform for financial planning and analysis by generating models from business data and conversational analytics.', url: '' },
  { name: 'Syllaby', category: 'Social Media', description: 'Effortlessly Create Viral Videos with Syllaby.io.', url: '' },
  { name: 'Gizmo', category: 'For Fun', description: 'An iOS App to create interactive puzzles, memes, toys, and mini-games.', url: '' },
  { name: 'Txt2Create', category: 'Generative Art', description: 'A tool to create videos, images, and animated content from text.', url: '' },
  { name: 'ReportCraft', category: 'Research', description: 'A tool to generate business reports from prompts.', url: '' },
  { name: 'WebTracker AI', category: 'Marketing', description: 'A tool to monitor competitors’ websites, pricing, and market trends with insights.', url: '' },
  { name: 'Archive', category: 'Social Media', description: 'A tool for influencer marketing to track, organize, and manage user-generated content.', url: '' },
  { name: 'KUSE AI', category: 'Productivity', description: 'A tool to organize information and create structured collaborative workspaces.', url: '' },
  { name: 'Stormy AI', category: 'Social Media', description: 'A tool for influencer marketing campaigns from creator discovery to performance tracking.', url: '' },
  { name: 'Lorean Labs', category: 'Marketing', description: 'A tool to generate video ads from product images and scripts.', url: '' },
  { name: 'SmythOS', category: 'Productivity', description: 'A no-code platform to build and deploy AI agents through visual drag-and-drop tools.', url: '' },
  { name: 'Fast Q&A', category: 'Chat', description: 'A tool to answer visitor questions directly on websites.', url: '' },
  { name: 'Yapify', category: 'Productivity', description: 'An email assistant that generates personalized, emails from voice commands by learning your writing style.', url: '' },
  { name: 'PhotoFox AI', category: 'Generative Art', description: 'A tool to generate product visuals and videos without traditional photoshoots.', url: '' },
  { name: 'Macaron', category: 'Productivity', description: 'An mobile app that creates personalized mini-apps within conversations.', url: '' },
  { name: 'Cobot', category: 'Productivity', description: 'A tool to manage tasks, emails, calendars, and meetings.', url: '' },
  { name: 'Matrix Game 2.0', category: 'Gaming', description: 'A tool to generate interactive real-time video in virtual environments with keyboard-controlled characters and cameras.', url: '' },
  { name: 'Zoer', category: 'Generative Code', description: 'A nocode tool to build internal applications and workflows.', url: '' },
  { name: 'Maskara AI', category: 'Research', description: 'A platform to conduct live debates between AI models to deliver the best answers without complex prompts.', url: '' },
  { name: 'IdeaBoard', category: 'Research', description: 'A platform with whiteboards that generates custom templates for collaborative brainstorming and planning from prompts.', url: '' },
  { name: 'Tasker AI', category: 'Productivity', description: 'A tool to execute tasks with digital workflows across applications using natural language commands.', url: '' },
  { name: 'WaveSpeed AI', category: 'Generative Art', description: 'A platform to generate images and videos from text, image, or audio prompts.', url: '' },
  { name: 'Simular Pro', category: 'Productivity', description: 'An desktop agent that automates workflows across computer.', url: '' },
  { name: 'Release0', category: 'Chat', description: 'A no-code platform for building chatbots and conversational forms across multiple channels.', url: '' },
  { name: 'VibeScan', category: 'Generative Code', description: 'A tool that scans and fixes vulnerabilities in AI-generated code with security checks and repairs.', url: '' },
  { name: 'Ten', category: 'Chat', description: 'A tool to build real-time multimodal conversational AI agents.', url: '' },
  { name: 'ReadyScriptPro', category: 'Copywriting', description: 'A tool to generate customized scripts and marketing content.', url: '' },
  { name: 'Functionize', category: 'Productivity', description: 'A tool to automate and manage enterprise software testing workflows.', url: '' },
  { name: 'TicketMine.ai', category: 'Productivity', description: 'A tool that extracts Configuration Item data from IT tickets to maintain CMDB accuracy.', url: '' },
  { name: 'Trails.so', category: 'Productivity', description: 'A tool to create step-by-step guides from recorded processes.', url: '' },
  { name: 'MemU', category: 'Productivity', description: 'A tool to organize and retrieve information for AI applications.', url: '' },
  { name: 'Elvity AI', category: 'Productivity', description: 'A tool to build explainable data pipelines from natural language.', url: '' },
  { name: 'Anything', category: 'Generative Code', description: 'A platform that transforms prompts into various digital assets.', url: '' },
  { name: 'Rork', category: 'Generative Code', description: 'A nocode platform that converts text descriptions into mobile apps.', url: '' },
  { name: 'MasterSheets', category: 'Productivity', description: 'A tool that transforms spreadsheets into web applications for business workflows.', url: '' },
  { name: 'VibeDash', category: 'Productivity', description: 'A tool to manage software projects with client collaboration.', url: '' },
  { name: 'CrePal', category: 'Generative Art', description: 'A tool to create and edit images, scripts to produce videos.', url: '' },
  { name: 'Context.ai', category: 'Generative Code', description: 'A tool to build RAG AI apps using internal knowledge bases.', url: '' },
  { name: 'FlowMetr', category: 'Productivity', description: 'A tool that monitors open-source AI models in production with real-time analytics, logging and alerting.', url: '' },
  { name: 'Amplify Security', category: 'Generative Code', description: 'A tool that detects and fixes code vulnerabilities.', url: '' },
  { name: 'Lindra AI', category: 'Productivity', description: 'An virtual employee that automates routine business tasks without coding.', url: '' },
  { name: 'Content Maxima', category: 'Copywriting', description: 'A marketing suite for SEO content creation from analysis and research.', url: '' },
  { name: 'Tenali', category: 'Marketing', description: 'An sales assistant for real-time support during calls by answering product questions, note-taking, and updating CRM records.', url: '' },
  { name: 'CodeFlash AI', category: 'Generative Code', description: 'A tool to optimize Python code performance while preserving functionality.', url: '' },
  { name: 'Botric AI', category: 'Chat', description: 'A tool for customer service with self learning, context-aware and integrates across digital platforms.', url: '' },
  { name: 'Recurse ML', category: 'Generative Code', description: 'A tool that scans pull requests to detect bugs and breaking changes.', url: '' },
  { name: 'Empromptu.ai', category: 'Prompt Guides', description: 'A tool to create, manage, share and optimize prompts through templates and collaboration.', url: '' },
  { name: 'Amplifa', category: 'Marketing', description: 'A platform to automate B2B lead generation and sales outreach.', url: '' },
];

const byCategory = tools.reduce((acc, t) => {
  // Ensure tool and category are valid before processing
  if (!t || typeof t.category !== 'string') {
    console.warn('Invalid tool object found:', t);
    return acc;
  }
  
  const key = t.category ? t.category.trim() : 'Uncategorized';
  
  if (!acc[key]) {
    acc[key] = [];
  }
  
  acc[key].push(t);
  return acc;
}, {});

const aiTools = {
  tools,
  byCategory,
  categories: Object.keys(byCategory).sort(),
  get(category) {
    return byCategory[category] || [];
  }
};

// Attach for browser use
if (typeof window !== 'undefined') {
  window.aiTools = aiTools;
}

// Export for CommonJS/Node if available
if (typeof module !== 'undefined' && module.exports) {
  module.exports = aiTools;
}


export default aiTools;
